---
# tasks file for jdk
- name: copy jdk.tar.gz to /usr/local/src
  vars:
    version: "8u301"
  copy:
    src: jdk-{{ version }}-linux-x64.tar.gz
    dest: /usr/local/src

- name: install jdk
  vars:
    version: "8u301"
    version2: "1.8.0_301"
  shell: |
    cd /usr/local/src
    tar -zxf jdk-{{ version }}-linux-x64.tar.gz
    mv jdk{{ version2 }} /usr/local/jdk
  args:
    creates: /usr/local/jdk

- name: copy jdk.sh to /etc/profile.d
  copy:
    src: jdk.sh
    dest: /etc/profile.d
