---
- hosts: all
  gather_facts: no
  tasks:
    - name: useradd
      user:
        name: "{{ user }}"
        password: "{{ password | password_hash('sha512') }}"
        state: present

    - name: add sudo to user
      lineinfile:
        path: /etc/sudoers.d/{{ user }}
        line: "{{ user }} ALL=(ALL) NOPASSWD:ALL"
        create: yes
      when: sudo is defined and sudo == "yes"

    - name: remove sudo from user
      file:
        path: /etc/sudoers.d/{{ user }}
        state: absent
      when: sudo is defined and sudo == "no"
