# optimize 1
- name: append line to /etc/rc.local
  blockinfile:
    path: /etc/rc.local
    block: |
      echo 512 > /proc/sys/net/core/somaxconn
      echo madvise > /sys/kernel/mm/transparent_hugepage/enabled

- name: chmod /etc/rc.local
  file:
    path: /etc/rc.local
    mode: o+x

- name: make hugepage effective immediately
  shell: |
    echo 512 > /proc/sys/net/core/somaxconn
    echo madvise > /sys/kernel/mm/transparent_hugepage/enabled

# optimize 2
- name: add file /etc/sysctl.d/91-redis.conf with content
  copy:
    dest: /etc/sysctl.d/91-redis.conf
    content: |
      vm.overcommit_memory = 1

- name: make sysctl.conf effective immediately
  shell: sysctl -p /etc/sysctl.d/91-redis.conf

- name: add redis PATH
  copy:
    dest: /etc/profile.d/redis.sh
    content: |
      export PATH=$PATH:/usr/local/redis/bin

