- name: check if redis-sentinel.log exists
  stat:
    path: /usr/local/redis/redis-sentinel.log
  register: redis_sentinel_log

- name: replace mymaster in redis-sentinel.conf
  replace:
    path: /usr/local/redis/redis-sentinel.conf
    regexp: "mymaster 127.0.0.1"
    replace: "mymaster {{groups['redis_master'][0]}}"
  when:  not redis_sentinel_log.stat.exists

- name: add auth-pass to sentinel.conf
  blockinfile:
    path: /usr/local/redis/redis-sentinel.conf
    block: |
      sentinel auth-pass mymaster {{redis_pass}}
      requirepass {{redis_pass}}
  when: not redis_sentinel_log.stat.exists

- name: copy redis-sentinel.service
  copy:
    src: redis-sentinel.service
    dest: /usr/lib/systemd/system/redis-sentinel.service

- name: Start redis-sentinel service and enable on boot
  systemd:
    name: redis-sentinel
    state: started
    enabled: yes
    daemon_reload: yes
