---
# tasks file for sftp

- name: add new config
  blockinfile:
    path: /etc/ssh/sshd_config
    block: |
      Match Group sftp
          ForceCommand       internal-sftp
          ChrootDirectory    /data/sftp/%u

- name: reload sshd
  systemd:
    name: sshd
    state: reloaded

- name: groupadd sftp
  group:
    name: sftp

- name: add user to group
  user:
    name: "{{ user }}"
    password: "{{ password | password_hash('sha512') }}"
    group: sftp
    shell: /sbin/nologin
    home: /upload
    create_home: no
  when:
    - user is defined
    - password is defined

- name: mkdir upload directory
  shell: |
    mkdir -p /data/sftp/{{ user }}/upload
    chown -R root:sftp /data/sftp/{{ user }}
    chown -R {{ user }}:sftp /data/sftp/{{ user }}/upload
  when:
    - user is defined
    - password is defined

