---
# tasks file for sftp

- name: comment default Subsystem
  replace:
    path: /etc/ssh/sshd_config
    regexp: '(^Subsystem.*openssh/sftp-server)'
    replace: '#\1'

- name: add new config
  blockinfile:
    path: /etc/ssh/sshd_config
    block: |
      Subsystem sftp internal-sftp
      Match Group sftp
          X11Forwarding      no
          AllowTcpForwarding no
          ForceCommand       internal-sftp
          ChrootDirectory    /data/sftp/%u

- name: reload sshd
  systemd:
    name: sshd
    state: reloaded

- name: groupadd sftp
  group:
    name: sftp

- name: add user and set group
  user:
    name: "{{ user }}"
    password: "{{ password | password_hash('sha512') }}"
    group: sftp
    shell: /sbin/nologin
    create_home: no
  when:
    - user is defined
    - password is defined

- name: mkdir sftp data directory
  file:
    path: /data/sftp/{{ user }}/data
    state: directory
  when:
    - user is defined
    - password is defined

- name: change owner of sftp's subdirectory
  file:
    path: /data/sftp/{{ user }}/data
    state: directory
    owner: "{{ user }}"
    group: sftp
  when:
    - user is defined
    - password is defined
