---
- name: gather installed packages
  package_facts:
    manager: auto

- name: install zabbix-agent
  dnf:
    name: https://repo.zabbix.com/zabbix/7.0/alma/8/x86_64/zabbix-agent-7.0.5-release1.el8.x86_64.rpm
    state: present
    disable_gpg_check: True
  when: "'zabbix-agent' not in ansible_facts.packages"

- name: replace Server=
  replace:
    path: /etc/zabbix/zabbix_agentd.conf
    regexp: "^Server=.*"
    replace: "Server={{zabbix_proxy}}"

- name: replace ServerActive=
  replace:
    path: /etc/zabbix/zabbix_agentd.conf
    regexp: "^ServerActive=.*"
    replace: "ServerActive={{zabbix_proxy}}"

- name: replace Hostname=
  replace:
    path: /etc/zabbix/zabbix_agentd.conf
    regexp: "^Hostname=.*"
    replace: "Hostname={{hostname}}"

- name: Start zabbix-agent service and enable on boot
  systemd:
    name: zabbix-agent
    state: started
    enabled: yes
