---
# tasks file for zabbix_yum
- name: install zabbix-agent
  dnf:
    name: https://repo.zabbix.com/zabbix/7.0/alma/8/x86_64/zabbix-agent-7.0.5-release1.el8.x86_64.rpm
    state: present
    disable_gpg_check: True

- name: replace string in /etc/zabbix/zabbix_agentd.conf 1
  replace:
    path: /etc/zabbix/zabbix_agentd.conf
    regexp: "=127.0.0.1$"
    replace: "={{zabbix_proxy}}"

- name: replace string in /etc/zabbix/zabbix_agentd.conf 2
  replace:
    path: /etc/zabbix/zabbix_agentd.conf
    regexp: "=Zabbix server$"
    replace: "={{hostname}}"

- name: Start zabbix-agent service and enable on boot
  systemd:
    name: zabbix-agent
    state: started
    enabled: yes
