- name: Install chrony
  yum:
    name: chrony
    state: present

- name: Start chrony and enable on boot
  systemd:
    name: chronyd
    state: started
    enabled: yes

- name: Synchronize time immediately
  shell: chronyc makestep
