- name: Disable selinux in config
  ansible.posix.selinux:
    state: disabled

- name: Register selinux variable
  shell: getenforce
  register: selinux

- name: Disable selinux on the fly
  shell: setenforce 0
  when: selinux.stdout != "Disabled"
