- name: Disable UseDNS
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^UseDNS.*"
    line: "UseDNS no"
  notify: reload sshd

- name: add root public key
  ansible.posix.authorized_key:
    user: root
    state: present
    key: "{{lookup('file', 'root.pub')}}"

- name: disable PasswordAuthentication
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^PasswordAuthentication.*"
    line: "PasswordAuthentication no"
  when: disable_password_auth is defined and disable_password_auth == "yes"
  notify: reload sshd

- name: disable ChallengeResponseAuthentication
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^ChallengeResponseAuthentication.*"
    line: "ChallengeResponseAuthentication no"
  when: disable_password_auth is defined and disable_password_auth == "yes"
  notify: reload sshd

- name: disable PermitRootLogin
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^PermitRootLogin.*"
    line: "PermitRootLogin no"
  when: permit_root_login is defined and permit_root_login == "no"
  notify: reload sshd
