- name: Disable UseDNS 1
  lineinfile:
    path: /etc/ssh/sshd_config
    line: "UseDNS no"
    state: present

- name: Disable UseDNS 2
  lineinfile:
    path: /etc/ssh/sshd_config
    line: "UseDNS yes"
    state: absent
  notify: "restart sshd"

- name: set root public key
  ansible.posix.authorized_key:
    user: root
    state: present
    key: "{{lookup('file', 'root.pub')}}"
